<?php
/**
 * Created by PhpStorm.
 * User: xmy 280564871@qq.com
 * Date: 2017/4/14
 * Time: 19:43
 */

namespace Admin\Controller;

use Admin\Model\CommentModel;
use App\Model\PointRecordModel;

class CommentController extends AdminController{

	public function _initialize()
	{
		$this->meta_title = "评论管理";
		return parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function lists($p=1){
		$model = new CommentModel();
		empty(I('game_id')) || $map['game_id'] = I('game_id');
		empty(I('status')) || $map['status'] = I('status');
		empty(I("account")) || $map['account'] = ["like","%".I("account")."%"];
		empty(I("time_start")) || $map['create_time'] = ["between",[strtotime(I("time_start")),empty(I("time_end"))?time():strtotime(I("time_end"))+86400-1]];
		$data = $model->getLists($map,'create_time desc',$p);

		//分页
		$count = $data['count'];
		$row = 10;
		if($count > $row){
			$page = new \Think\Page($count, $row);
			$page->setConfig('theme','%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
			$this->assign('_page', $page->show());
		}

		$this->assign("data",$data['data']);
		$this->display();
	}


	/**
	 * 审核
	 * @param $id   评论ID
	 * author: xmy 280564871@qq.com
	 */
	public function set_status($id){
		$model = new CommentModel();
		$data = $model->where(['id'=>$id])->find();
		$result = $model->where(['id'=>$id])->setField("status",1);
		if($result){
			$point = new PointRecordModel();
			$point->addPointByType("comment",get_user_id($data['account']));
			$this->success("审核成功",U('lists'));
		}else{
			$this->error("审核失败");
		}
	}
}