<?php
/**
 * Created by PhpStorm.
 * User: xmy 280564871@qq.com
 * Date: 2017/4/1
 * Time: 10:22
 */

namespace Admin\Controller;


use Admin\Model\PointRecordModel;

class PointRecordController extends ThinkController{

	public function _initialize()
	{
		$this->meta_title = "积分记录";
		return parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function lists($p=1){
		$model = new PointRecordModel();
		empty(I('type_id')) || $map['pr.type_id'] = I('type_id');
		empty(I("account")) || $map['u.account'] = ["like","%".I("account")."%"];
		empty(I("time_start")) || $map['pr.create_time'] = ["between",[strtotime(I("time_start")),empty(I("time_end"))?time():strtotime(I("time_end"))+86400-1]];
		$data = $model->getLists($map,'create_time desc',$p);

		//分页
		$count = $data['count'];
		$row = 10;
		if($count > $row){
			$page = new \Think\Page($count, $row);
			$page->setConfig('theme','%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
			$this->assign('_page', $page->show());
		}

		$this->assign("data",$data['data']);
		$this->display();
	}

}