<?php
/**
 * Created by PhpStorm.
 * User: xmy 280564871@qq.com
 * Date: 2017/4/1
 * Time: 10:22
 */

namespace Admin\Controller;


class PointTypeController extends ThinkController{


	public function _initialize()
	{
		$this->meta_title = "积分设置";
		return parent::_initialize(); // TODO: Change the autogenerated stub
	}

	/**
	 * 列表
	 * author: xmy 280564871@qq.com
	 */
	public function lists($p=1){
		$data = D("PointType")->getLists('','create_time desc',$p);
		$this->assign("data",$data['data']);

		//分页
		$count = $data['count'];
		$row = 10;
		if($count > $row){
			$page = new \Think\Page($count, $row);
			$page->setConfig('theme','%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
			$this->assign('_page', $page->show());
		}

		$this->display();
	}

	/**
	 * 编辑
	 * @param null $id
	 * author: xmy 280564871@qq.com
	 */
	public function edit($id){
		if(IS_POST){
			$model = D("PointType");
			$result = $model->edit($id);
			if($result !== false){
				$this->success("修改成功！",U('lists'));
			}else{
				$this->error("修改失败：".$model->getError());
			}

		}else{
			$data = D("PointType")->find($id);
			$this->assign("data",$data);
			$this->display();
		}
	}

}