<?php
/**
 * Created by PhpStorm.
 * User: xmy 280564871@qq.com
 * Date: 2017/4/10
 * Time: 14:29
 */

namespace Admin\Controller;

use Admin\Model\ShareRecordModel;

class ShareRecordController extends ThinkController{

	public function _initialize()
	{
		$this->meta_title = "邀请好友奖励";
		return parent::_initialize(); // TODO: Change the autogenerated stub
	}

	public function lists($p=1){
		$model = new ShareRecordModel();
		empty(I("invite_account")) || $map['invite_account'] = ["like","%".I("invite_account")."%"];
		empty(I("time_start")) || $map['create_time'] = ["between",[strtotime(I("time_start")),empty(I("time_end"))?time():strtotime(I("time_end"))+86400-1]];
		$data = $model->getInviteRecord($map,$p);

		//分页
		$count = $data['count'];
		$row = 10;
		if($count > $row){
			$page = new \Think\Page($count, $row);
			$page->setConfig('theme','%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
			$this->assign('_page', $page->show());
		}

		$this->assign("data",$data['data']);
		$this->display();
	}

	public function detail($id,$p=1){
		$model = new ShareRecordModel();
		$map['invite_id'] = $id;
		$data = $model->getDetail($map,$p);
		$this->assign("data",$data['data']);
		$this->display();
	}
}